/**
 * PDASServices.java
 *
 * This file was auto-generated from WSDL
 * by the Apache Axis 1.4 Apr 22, 2006 (06:55:48 PDT) WSDL2Java emitter.
 */

package com.app.das.webservices;

public interface PDASServices extends java.rmi.Remote {
    public java.lang.String getString(java.lang.String name) throws java.rmi.RemoteException;
    public java.lang.String getCode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public java.lang.String getAuthentication(java.lang.String ID, java.lang.String password, java.lang.String AD_DOMAIN) throws java.rmi.RemoteException;
    public int getOrderInfo() throws java.rmi.RemoteException;
    public int cancelJob(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getScenario(long masterId) throws java.rmi.RemoteException;
    public int updateRoleInfo(java.lang.String roleInfoDO) throws java.rmi.RemoteException;
    public int getBill(int bill) throws java.rmi.RemoteException;
    public java.lang.String getDecryption(java.lang.String strSSOKey, java.lang.String strMacHex, java.lang.String strSSOText) throws java.rmi.RemoteException;
    public java.lang.String getEncription(java.lang.String strSSOKey, java.lang.String strMacHex, java.lang.String strSSOEnc) throws java.rmi.RemoteException;
    public java.lang.String getLogin(java.lang.String userId, java.lang.String password) throws java.rmi.RemoteException;
    public java.lang.String getCartInfo(long cartNo, java.lang.String reqUserId) throws java.rmi.RemoteException;
    public java.lang.String getVideoPageInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getFilePathInfo(long contentId) throws java.rmi.RemoteException;
    public java.lang.String getVideoPageMetaInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getVideoPageContentsInfoList(long masterId) throws java.rmi.RemoteException;
    public int insertBoardInfo(java.lang.String boardInfoDO) throws java.rmi.RemoteException;
    public int updateBoardInfo(java.lang.String boardInfoDO) throws java.rmi.RemoteException;
    public void deleteBoardInfo(int boardId) throws java.rmi.RemoteException;
    public java.lang.String getBoardInfo(java.lang.String boardDO) throws java.rmi.RemoteException;
    public java.lang.String getPreviewInfo(int master_id) throws java.rmi.RemoteException;
    public java.lang.String getPreviewAttachInfo(int master_id) throws java.rmi.RemoteException;
    public java.lang.String insertErrorInfo(java.lang.String errorRegisterDO) throws java.rmi.RemoteException;
    public int insertPhotoinfo(java.lang.String photoInfoDO) throws java.rmi.RemoteException;
    public java.lang.String insertCornerinfo(long masterId, java.lang.String cornerInfo) throws java.rmi.RemoteException;
    public int insertContentsMappinfo(long masterId, java.lang.String contentMappInfo) throws java.rmi.RemoteException;
    public int insertMyCatalog(java.lang.String myCatalogDO) throws java.rmi.RemoteException;
    public int deleteMyCatalog(java.lang.String myCatalogDO) throws java.rmi.RemoteException;
    public java.lang.String insertAnnotinfo(long masterId, java.lang.String annotInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getCodeList(java.lang.String codeDO) throws java.rmi.RemoteException;
    public java.lang.String getCodeInfo(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int insertCodeInfo(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int updateCodeInfo(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int deleteCodeInfo(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int insertScenario(java.lang.String scenarioDO) throws java.rmi.RemoteException;
    public int deleteScenario(long master_id) throws java.rmi.RemoteException;
    public int insertRelationMaster(long parent_master_id, long child_master_id) throws java.rmi.RemoteException;
    public int deleteRelationMaster(long parent_master_id, long child_master_id) throws java.rmi.RemoteException;
    public java.lang.String getRelationMaster(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getRelationTotaly(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getScenario2(java.lang.String senario) throws java.rmi.RemoteException;
    public java.lang.String getMyCatalogBySort(java.lang.String myCatalogDO) throws java.rmi.RemoteException;
    public java.lang.String getMyCatalog(java.lang.String myCatalogDO) throws java.rmi.RemoteException;
    public java.lang.String deletePhotoFiles(java.lang.String photoInfo) throws java.rmi.RemoteException;
    public java.lang.String insertAttachFile(java.lang.String attachFileInfo) throws java.rmi.RemoteException;
    public int updateDownCartState(long cartNo, java.lang.String cartState, java.lang.String title) throws java.rmi.RemoteException;
    public int updateDownCart(java.lang.String downCartDO) throws java.rmi.RemoteException;
    public int updateCartContInfo(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public int updateStCartContInfo(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public int updateDatastatCd(long masterID, java.lang.String secArchId, java.lang.String secArchNm) throws java.rmi.RemoteException;
    public int updateVd_qlty(int ctID, java.lang.String vd_qlty, java.lang.String asp_rto_cd) throws java.rmi.RemoteException;
    public int updateMetadataStatusCd(long masterID, java.lang.String statCd, java.lang.String modrid, java.lang.String moddt, java.lang.String lock_stat_cd, java.lang.String error_stat_cd) throws java.rmi.RemoteException;
    public int updateModUserid(long masterId, java.lang.String userId) throws java.rmi.RemoteException;
    public int updateSDIngestStatus(java.lang.String itemId, java.lang.String ingestStatus) throws java.rmi.RemoteException;
    public java.lang.String insertTapeinfo(long masterId, java.lang.String IDhead, java.lang.String userId, java.lang.String year) throws java.rmi.RemoteException;
    public int getLogRcdPeriod(int dasEqId, java.lang.String dasEqPsCd) throws java.rmi.RemoteException;
    public void deleteAllCartInfo(long cartNo) throws java.rmi.RemoteException;
    public java.lang.String deleteContentFiles(int days) throws java.rmi.RemoteException;
    public java.lang.String deleteKfrmFiles(java.lang.String krfmFileList) throws java.rmi.RemoteException;
    public void deleteCartInfoList(long cartNo, int seq) throws java.rmi.RemoteException;
    public void deleteContentItemList(java.lang.String masterIdGRP) throws java.rmi.RemoteException;
    public java.lang.String getAnnotInfoInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getCartContList(long cartNo) throws java.rmi.RemoteException;
    public java.lang.String getAttachFileInfoList(long mothrId) throws java.rmi.RemoteException;
    public java.lang.String getContentsPreInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getClipHeaderImgInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getContentsInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getCornerHeaderImgInfo(long ctId, long cnId) throws java.rmi.RemoteException;
    public java.lang.String getCornerInfoList(long masterId, java.lang.String keyWord) throws java.rmi.RemoteException;
    public java.lang.String getFLIngestCommonCodeList() throws java.rmi.RemoteException;
    public java.lang.String getFlIngestLastCommandList() throws java.rmi.RemoteException;
    public java.lang.String getIngestServerList(java.lang.String clfCd) throws java.rmi.RemoteException;
    public java.lang.String getSDIngestCommonCodeList() throws java.rmi.RemoteException;
    public java.lang.String getSDIngestStatusInfo(java.lang.String tapeItemId) throws java.rmi.RemoteException;
    public java.lang.String getSDIngestRefreshTapeInfo(java.lang.String tapeId) throws java.rmi.RemoteException;
    public java.lang.String getTapeOutIngestCartItemInfo(long cartNo) throws java.rmi.RemoteException;
    public java.lang.String getTapeOutIngestCommonCodeList() throws java.rmi.RemoteException;
    public java.lang.String getTapeOutIngestDownCartInfoList(java.lang.String reqUserId, int resolution, boolean reqDtChk, java.lang.String reqDt) throws java.rmi.RemoteException;
    public java.lang.String getSDTapeInfoList(java.lang.String reqNum, java.lang.String pgmNm, java.lang.String ingestStatus, boolean onAirDateSearch, java.lang.String onAirDateStart, java.lang.String onAirDateEnd) throws java.rmi.RemoteException;
    public java.lang.String getProgramInfoList(java.lang.String pgmNm) throws java.rmi.RemoteException;
    public java.lang.String getPgmContentsInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getKeyFrameInfoInfoList(long ctId, int fromSeq, int toSeq) throws java.rmi.RemoteException;
    public java.lang.String getManagementInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getMediaInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getModDatastatcd(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getPhotoInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getReflectionInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getStorageIP() throws java.rmi.RemoteException;
    public java.lang.String getCommonInfoList(java.lang.String clfCd) throws java.rmi.RemoteException;
    public java.lang.String getTapeInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getMetadataInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getErrorInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getModeUserInfoList(long masterId) throws java.rmi.RemoteException;
    public java.lang.String getPgmInfoFromName(java.lang.String programInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getPgmInfoFromName2(java.lang.String pgmNm) throws java.rmi.RemoteException;
    public java.lang.String getLastPgmInfoXmllist(java.lang.String programDO) throws java.rmi.RemoteException;
    public java.lang.String getLastPgmInfolist(java.lang.String pgmNm) throws java.rmi.RemoteException;
    public java.lang.String getLastPgmInfolistByPgmId(long pgmId) throws java.rmi.RemoteException;
    public java.lang.String getLastPgmInfolistByPgmId2(long pgmId, java.lang.String brd_dd) throws java.rmi.RemoteException;
    public java.lang.String getPgmInfoFromMasterid(int episNo, long pgmId) throws java.rmi.RemoteException;
    public java.lang.String getPlayMediaInfo(long CTI_ID) throws java.rmi.RemoteException;
    public java.lang.String getPlayContentInfo(long masterID) throws java.rmi.RemoteException;
    public java.lang.String getPgm_cd() throws java.rmi.RemoteException;
    public int deleteAttachFile(java.lang.String attachFilename, java.lang.String file_type, java.lang.String clf_cd) throws java.rmi.RemoteException;
    public int insertPhotoDownloadInfo(long phot_ID, java.lang.String REQ_ID, long PGM_ID) throws java.rmi.RemoteException;
    public int insertPhotoDownInfo(java.lang.String photo) throws java.rmi.RemoteException;
    public int updateContentMediaInfo(long master_ID, java.lang.String aud_type_cd, java.lang.String record_type_cd, java.lang.String me_cd, java.lang.String color_cd) throws java.rmi.RemoteException;
    public int updateDatacdWithMasterid_XML(java.lang.String strXML) throws java.rmi.RemoteException;
    public java.lang.String insertERPTapeInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String updateERPTapeInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getUserAuthCD(java.lang.String userID) throws java.rmi.RemoteException;
    public java.lang.String getDownCartList(java.lang.String reqUsrID, java.lang.String dateStart, java.lang.String dateEnd, java.lang.String down_nm) throws java.rmi.RemoteException;
    public java.lang.String getBasicPageInfo(long masterId) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV(long cti_id) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV_NM(long ct_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV_KFRM(long ct_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateKFRM(long ct_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public int unlockByUserID(java.lang.String strUserID) throws java.rmi.RemoteException;
    public java.lang.String getMergedFilenames(long master_id) throws java.rmi.RemoteException;
    public java.lang.String getMasterDataTotaly(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getMasterDataAll(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getRelationScean(long master_id) throws java.rmi.RemoteException;
    public int multiLockUnlock(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getStoryboardData(long masterId, java.lang.String keyword) throws java.rmi.RemoteException;
    public java.lang.String getBoardList(java.lang.String boardInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getOutsiderEmployeeRoleList(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int updateOutEmployeeRole(java.lang.String nonEmployeeInfoDO) throws java.rmi.RemoteException;
    public int amendPassword(java.lang.String userId, java.lang.String beforePasswd, java.lang.String afterPasswd) throws java.rmi.RemoteException;
    public int insertNonEmployeeRole(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int deleteScreenAuthentication(java.lang.String codeDO) throws java.rmi.RemoteException;
    public java.lang.String getTotalChangelist(java.lang.String programDO) throws java.rmi.RemoteException;
    public java.lang.String getEmployeeList(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int updateEmployeeRole(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int updateEmployeeRoleYN(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public java.lang.String insertEmployeeRole(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getDisCardList(java.lang.String discardDO) throws java.rmi.RemoteException;
    public int insertDisuse(java.lang.String discardDO) throws java.rmi.RemoteException;
    public int cancelDisuse(int master_id) throws java.rmi.RemoteException;
    public int cancelDisuse2(java.lang.String master_id) throws java.rmi.RemoteException;
    public int insertUse(java.lang.String discardDO) throws java.rmi.RemoteException;
    public java.lang.String getHyenDisCardList(java.lang.String discardDO) throws java.rmi.RemoteException;
    public java.lang.String getHyenUseList(java.lang.String discardDO) throws java.rmi.RemoteException;
    public java.lang.String getJanrCodeList(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int creatBcode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int creatMcode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int creatScode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int updateBcode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int updateMcode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public int updateScode(java.lang.String codeDO) throws java.rmi.RemoteException;
    public java.lang.String getPgmList(java.lang.String programInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getPgmInfo(java.lang.String pgm_cd) throws java.rmi.RemoteException;
    public java.lang.String getParentsCD(java.lang.String pgm_cd) throws java.rmi.RemoteException;
    public int insertPgmcd(java.lang.String programInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getSearchRelationInfo(java.lang.String programDO) throws java.rmi.RemoteException;
    public int updatePgmcd(java.lang.String programInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getSubsiServerList(java.lang.String subsiInfoDO) throws java.rmi.RemoteException;
    public int insertSubsiServer(java.lang.String subsiInfoDO) throws java.rmi.RemoteException;
    public int updateSubsiServer(java.lang.String subsiInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getCopyList(java.lang.String copyDO) throws java.rmi.RemoteException;
    public int insertCopy(java.lang.String copyDO) throws java.rmi.RemoteException;
    public int updateCopy(java.lang.String copyDO) throws java.rmi.RemoteException;
    public java.lang.String getDownloadRequestList(java.lang.String commonDO) throws java.rmi.RemoteException;
    public java.lang.String getDownloadRequestDetailList(java.lang.String cartNo, java.lang.String user_id) throws java.rmi.RemoteException;
    public int updateDownloadRequestDetail(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public int updateDownloadRequestOutSourcingDetail(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_TOTAL_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_COL_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_DISUSE_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_ARRA_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_GNR_USE_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_GNR_USE2_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PGM_USE_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PHOT_COL_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PHOT_REG_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PHOT_TOTAL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PHOT_PGM_TOTAL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PHOT_DISUSE_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PHOT_USE_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_GNR_ARCH_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PGM_ARCH_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_DEPT_USE_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_DEPT_ARCH_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_DEPT_ARCH_DTL_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_DEPT_ARCH_REQ_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PGM_ARCH_DTL_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSTAT_PGM_ARCH_REQ_TBL_List(java.lang.String statisticsConditionDO) throws java.rmi.RemoteException;
    public java.lang.String insertAddTask(java.lang.String addTask) throws java.rmi.RemoteException;
    public java.lang.String completeDown(int num) throws java.rmi.RemoteException;
    public java.lang.String completeArchive(java.lang.String job_status, long cti_id) throws java.rmi.RemoteException;
    public java.lang.String getTmStatus(int taskID) throws java.rmi.RemoteException;
    public int getTmStatusAll(java.lang.String getTmStatusAll) throws java.rmi.RemoteException;
    public int updateTmStatusAll(java.lang.String getTmStatusAll) throws java.rmi.RemoteException;
    public java.lang.String getPhotoList(int master_id) throws java.rmi.RemoteException;
    public java.lang.String getAttachPhotoList(java.lang.String photInfoDO) throws java.rmi.RemoteException;
    public int updatPhotoCount(java.lang.String photInfoDO) throws java.rmi.RemoteException;
    public int insertAttachPhotoinfo(java.lang.String photoInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getDepInfoList(java.lang.String depInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getDepInfo() throws java.rmi.RemoteException;
    public java.lang.String getDepCocdInfo(java.lang.String cocd) throws java.rmi.RemoteException;
    public java.lang.String getDepList(java.lang.String depInfoDO) throws java.rmi.RemoteException;
    public int insertDepInfo(java.lang.String depInfoDO) throws java.rmi.RemoteException;
    public int updateDepInfo(java.lang.String depInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getAuthorInfoList(java.lang.String authorDO) throws java.rmi.RemoteException;
    public int updatAuthorInfo(java.lang.String authorDO) throws java.rmi.RemoteException;
    public java.lang.String getERPAppointList(java.lang.String erpappointDO) throws java.rmi.RemoteException;
    public java.lang.String getERPAppointMaxSeq() throws java.rmi.RemoteException;
    public int insertERPAppoint(java.lang.String erpappointDO) throws java.rmi.RemoteException;
    public int updateTotalChange(java.lang.String totalChangeInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getUseInfoList(java.lang.String useInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getProgramInfo(java.lang.String title) throws java.rmi.RemoteException;
    public java.lang.String getAvailable() throws java.rmi.RemoteException;
    public java.lang.String getTodayList(java.lang.String todayDO) throws java.rmi.RemoteException;
    public java.lang.String getGoodList(java.lang.String goodDO) throws java.rmi.RemoteException;
    public java.lang.String getParentsInfo(java.lang.String pgm_nm) throws java.rmi.RemoteException;
    public java.lang.String getScanDisk() throws java.rmi.RemoteException;
    public java.lang.String getStorageInfo(java.lang.String storageDO) throws java.rmi.RemoteException;
    public java.lang.String getPreProcessing(java.lang.String preProcessingDO) throws java.rmi.RemoteException;
    public java.lang.String getArchPreProcessing(java.lang.String conditionDO) throws java.rmi.RemoteException;
    public int insertMetadat(java.lang.String metadataMstInfoDO) throws java.rmi.RemoteException;
    public int insertCopyMetadat(java.lang.String metadataMstInfoDO) throws java.rmi.RemoteException;
    public int insertPdsPgmInfoAll(java.lang.String pdsInfoDO) throws java.rmi.RemoteException;
    public int insertPdsPgmInfo(java.lang.String pdsInfoDO) throws java.rmi.RemoteException;
    public int insertPdsPgmUserInfo(java.lang.String pgmUserInfoDO) throws java.rmi.RemoteException;
    public int insertPdsPgmUserInfoAll(java.lang.String pgmUserInfoDO) throws java.rmi.RemoteException;
    public int insertPdsMappInfo(java.lang.String pdsMappDO) throws java.rmi.RemoteException;
    public int insertNLEandDTL(long ct_id) throws java.rmi.RemoteException;
    public long insertDTL(long ct_id) throws java.rmi.RemoteException;
    public java.lang.String getMyDownloadRequestList(java.lang.String commonDO) throws java.rmi.RemoteException;
    public java.lang.String getMyDownloadRequestDetailList(java.lang.String cartNo, java.lang.String user_id) throws java.rmi.RemoteException;
    public int deleteNLE(long ct_id) throws java.rmi.RemoteException;
    public int deleteNLEForDown(long cart_no) throws java.rmi.RemoteException;
    public java.lang.String getSearchText(java.lang.String searchInfoDO) throws java.rmi.RemoteException;
    public int insertERPUserInfo(java.lang.String erpappointDO) throws java.rmi.RemoteException;
    public java.lang.String insertPassword(java.lang.String pawd) throws java.rmi.RemoteException;
    public java.lang.String updateInitPassword(java.lang.String user_id) throws java.rmi.RemoteException;
    public java.lang.String getRelationLink(long masterId) throws java.rmi.RemoteException;
    public int updateERPAppoint(java.lang.String erpappointDO) throws java.rmi.RemoteException;
    public int insertOtherUserInfo(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int insertOtherDepInfo(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getMyDownloadAprroveList(java.lang.String commonDO) throws java.rmi.RemoteException;
    public java.lang.String getMyDownloadAprroveDetailList(java.lang.String cartNo, java.lang.String user_id) throws java.rmi.RemoteException;
    public java.lang.String getMainList() throws java.rmi.RemoteException;
    public java.lang.String getOtherEmployeeList(java.lang.String sbs_user_id) throws java.rmi.RemoteException;
    public java.lang.String getOhterDepInfoList(java.lang.String cocd, java.lang.String dept_cd) throws java.rmi.RemoteException;
    public java.lang.String getMainKeyList() throws java.rmi.RemoteException;
    public int insertRealEmployeeRole(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int insertPDSArchive(java.lang.String pdasArchiveDO) throws java.rmi.RemoteException;
    public java.lang.String insertIfCmsArchive(java.lang.String pdasArchiveDO) throws java.rmi.RemoteException;
    public int updatePDSArchiveStatus(java.lang.String pdasArchiveDO) throws java.rmi.RemoteException;
    public java.lang.String updateIfCmsArchiveStatus(java.lang.String pdasArchiveDO) throws java.rmi.RemoteException;
    public java.lang.String updateAccept(long master_id) throws java.rmi.RemoteException;
    public java.lang.String updateArrange(long master_id) throws java.rmi.RemoteException;
    public java.lang.String updateArrange2(long master_id, java.lang.String user_id) throws java.rmi.RemoteException;
    public java.lang.String getPDSList(java.lang.String pdsDownDO) throws java.rmi.RemoteException;
    public java.lang.String getNDSList(java.lang.String ndsDownDO) throws java.rmi.RemoteException;
    public java.lang.String getRepBaseInfo(long master_id) throws java.rmi.RemoteException;
    public java.lang.String isValidUserWithToken(java.lang.String tokenDO) throws java.rmi.RemoteException;
    public java.lang.String isValidUser(java.lang.String tokenDO) throws java.rmi.RemoteException;
    public java.lang.String insertReqJobTC(java.lang.String tcBeanDO) throws java.rmi.RemoteException;
    public java.lang.String updateTcState(java.lang.String tcBeanDO) throws java.rmi.RemoteException;
    public java.lang.String insertReqComTc(java.lang.String tcBeanDO) throws java.rmi.RemoteException;
    public int updateRealEmployeeRole(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int updateRealEmployeeRoleYN(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public java.lang.String updateRealEmployeeRoleCharYN(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public java.lang.String insertPdsFolderAll2(java.lang.String user_id) throws java.rmi.RemoteException;
    public int insertPdsFolderAll() throws java.rmi.RemoteException;
    public java.lang.String insertNdsFolderAll(java.lang.String user_id) throws java.rmi.RemoteException;
    public java.lang.String getSupHeadList(java.lang.String COCD) throws java.rmi.RemoteException;
    public java.lang.String getAttachFileInfo(long master_id) throws java.rmi.RemoteException;
    public int updateErrorDownCart(java.lang.String downCartDO) throws java.rmi.RemoteException;
    public java.lang.String getSearchTextForDetail(java.lang.String searchInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getSearchTextForKey(java.lang.String searchInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getBoardAtaachInfo(int boardId) throws java.rmi.RemoteException;
    public int insertBoardAtaachInfo(java.lang.String fileInfoDO) throws java.rmi.RemoteException;
    public int updateBoardAtaachInfo(java.lang.String fileInfoDO) throws java.rmi.RemoteException;
    public java.lang.String updateRsv_Prd_DD(java.lang.String rsv_prd_cd, long master_id) throws java.rmi.RemoteException;
    public int deleteBoardAttachFile(java.lang.String attachFilename, java.lang.String fl_path, int boardId) throws java.rmi.RemoteException;
    public java.lang.String getSupHtpoList(java.lang.String COCD) throws java.rmi.RemoteException;
    public java.lang.String getSupHeadList2(java.lang.String deptcd) throws java.rmi.RemoteException;
    public java.lang.String getDepinfoList(java.lang.String deptcd) throws java.rmi.RemoteException;
    public java.lang.String getDepinfoForuserList(java.lang.String deptcd) throws java.rmi.RemoteException;
    public java.lang.String getApproveInfoList(java.lang.String apprveDO) throws java.rmi.RemoteException;
    public java.lang.String getApproveInfo(java.lang.String apprveDO) throws java.rmi.RemoteException;
    public int insertApproveInfo(java.lang.String apprveDO) throws java.rmi.RemoteException;
    public void deleteApproveInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public int deleteApproveInfo2(java.lang.String user_no, java.lang.String dept_cd) throws java.rmi.RemoteException;
    public java.lang.String getProgramInfo2(java.lang.String title) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV_NMforClient(long ct_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV_NMforMainSean(long master_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV_KFRMforClient(long ct_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateWMV_KFRMMainSean(long master_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateKFRMforClient(long ct_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String recreateKFRMMainSean(long master_id, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String getEmployeeListForApp(java.lang.String dep_cd, java.lang.String user_nm) throws java.rmi.RemoteException;
    public java.lang.String getBoardInfoForPopUp(java.lang.String today) throws java.rmi.RemoteException;
    public int updatePhotInfo(java.lang.String photoInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getRoleForLogin(java.lang.String user_id) throws java.rmi.RemoteException;
    public int insertArchiveReq(java.lang.String archiveReqDO) throws java.rmi.RemoteException;
    public java.lang.String updateArchiveReq(java.lang.String archiveReqDO) throws java.rmi.RemoteException;
    public java.lang.String insertComArchivereq(java.lang.String archiveReqDO) throws java.rmi.RemoteException;
    public int updatePasswd(java.lang.String employeeInfoDO) throws java.rmi.RemoteException;
    public int insertNleArchive(java.lang.String nleDO) throws java.rmi.RemoteException;
    public java.lang.String testServiceTest(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testDownloadService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testReportService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testGetResArchieve(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testNleIngestService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testGetResDelete(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testDeleteContentService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testIngestReportService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testArchiveReportService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testGetResCopy(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testFileIngestService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testAddClipInfoService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testGetResUpdate(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testGetResRestore(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testArchiveSchedulerService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testDeleteClipInfoService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String testArchiveService(java.lang.String arg0) throws java.rmi.RemoteException;
    public java.lang.String getCartInfoForUser(java.lang.String cartItemDO) throws java.rmi.RemoteException;
    public java.lang.String getRoleCode() throws java.rmi.RemoteException;
    public java.lang.String deleteMasterScean(long master_id) throws java.rmi.RemoteException;
    public java.lang.String deleteMasterScean2(java.lang.String deleteDO) throws java.rmi.RemoteException;
    public int updateEdtrId(java.lang.String code, java.lang.String ct_ids) throws java.rmi.RemoteException;
    public java.lang.String getAnnotCode() throws java.rmi.RemoteException;
    public java.lang.String updateRetryArchive(long seq) throws java.rmi.RemoteException;
    public java.lang.String updateRetryArchiveByCtId(long ct_id) throws java.rmi.RemoteException;
    public java.lang.String insertCornerContinfo(long cn_id, java.lang.String cnInfoDO) throws java.rmi.RemoteException;
    public java.lang.String deletePDSArchive(java.lang.String deleteDO) throws java.rmi.RemoteException;
    public java.lang.String insertMediaId() throws java.rmi.RemoteException;
    public java.lang.String getRoleInfoList(java.lang.String roleInfoDO) throws java.rmi.RemoteException;
    public java.lang.String updateDataStatCd(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getClipInfoList(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getStorageCheck(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String updateIngestStatus(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getCocdForChennel(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getChennelInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getArchiveRoute(java.lang.String xml) throws java.rmi.RemoteException;
    public int insertNLEDTL(java.lang.String xml) throws java.rmi.RemoteException;
    public int insertDtlInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getAutoArchvieList(java.lang.String autoDO) throws java.rmi.RemoteException;
    public int updateAutoArchvie(java.lang.String autoDO) throws java.rmi.RemoteException;
    public int insertManualArchive(java.lang.String media_id) throws java.rmi.RemoteException;
    public java.lang.String getManualInfo(java.lang.String manualArchiveDO) throws java.rmi.RemoteException;
    public int insertManual(java.lang.String manualArchiveDO) throws java.rmi.RemoteException;
    public java.lang.String getMetadatInfoList(java.lang.String conditionDO) throws java.rmi.RemoteException;
    public java.lang.String getSceanInfo(long master_id) throws java.rmi.RemoteException;
    public java.lang.String getBaseInfo(long master_id) throws java.rmi.RemoteException;
    public int updateMetadat(java.lang.String metadataMstInfoDO) throws java.rmi.RemoteException;
    public int insertRoleInfo(java.lang.String roleInfoDO) throws java.rmi.RemoteException;
    public java.lang.String insertComMedia(java.lang.String tcBeanDO) throws java.rmi.RemoteException;
    public java.lang.String getRoleInfoForChennel(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String logHistory(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getLogInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getApproveInfoForChennel(java.lang.String apprveDO) throws java.rmi.RemoteException;
    public int insertApproveInfoForChennel(java.lang.String apprveDO) throws java.rmi.RemoteException;
    public java.lang.String getApproveInfoListForChennel(java.lang.String apprveDO) throws java.rmi.RemoteException;
    public void deleteApproveInfoForChennel(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getArchiveStatusList(java.lang.String archiveInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getManualArchiveInfo(java.lang.String manualArchiveDO) throws java.rmi.RemoteException;
    public java.lang.String getDtlInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String insertDownCartInfo(java.lang.String downCartDO) throws java.rmi.RemoteException;
    public java.lang.String insertCartContInfo(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public java.lang.String insertStDownCartInfo(java.lang.String downCartDO_cartContDO) throws java.rmi.RemoteException;
    public java.lang.String insertStCartContInfo(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public java.lang.String getLogInOutInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public int updateStDownCart(java.lang.String downCartDO) throws java.rmi.RemoteException;
    public java.lang.String getArchiveInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getTCinfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getTminfo(java.lang.String xml) throws java.rmi.RemoteException;
    public int changePriority(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getDetailInfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getManualDeleteList(java.lang.String xml) throws java.rmi.RemoteException;
    public int manualDelete(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getErroeList(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getServerList(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String updateCopyRequest(java.lang.String useInfoDO) throws java.rmi.RemoteException;
    public int updateMediaCilpStatus(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getJobList(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String updateWmvStatus(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String insertIfCmsDownCartInfo(java.lang.String downCartDO_cartContDO) throws java.rmi.RemoteException;
    public java.lang.String updateIfCmsDownloadApprove(java.lang.String cartContDO) throws java.rmi.RemoteException;
    public java.lang.String getRoleForLoginInMonitoring(java.lang.String user_id) throws java.rmi.RemoteException;
    public java.lang.String getGroupForMaster(long master_id) throws java.rmi.RemoteException;
    public java.lang.String getSceanInfoForIfCms(long ct_id) throws java.rmi.RemoteException;
    public java.lang.String tryAgain(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getDowninfo(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getManualJobinfo(java.lang.String xml) throws java.rmi.RemoteException;
    public int updateRoleInfoForMonitoring(java.lang.String roleInfoDO) throws java.rmi.RemoteException;
    public java.lang.String getDepinfoForuserListFormonitoring(java.lang.String deptcd) throws java.rmi.RemoteException;
    public java.lang.String getMyArchiveRequestList(java.lang.String commonDO) throws java.rmi.RemoteException;
    public java.lang.String getDowninfoForIfCms(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getJobStatus(java.lang.String xml) throws java.rmi.RemoteException;
    public int updateEquipMentStatus(java.lang.String xml) throws java.rmi.RemoteException;
    public java.lang.String getGroupForMasterForClient(long master_id) throws java.rmi.RemoteException;
    public java.lang.String getRoleCodeForMonitoring() throws java.rmi.RemoteException;
    public java.lang.String getAuthorForMonitoring(java.lang.String role_cd) throws java.rmi.RemoteException;
    public java.lang.String isVideoReleateYN(long master_id, long ct_id) throws java.rmi.RemoteException;
}
